import type {
  PAGE_QUERY_RESULT,
  POST_QUERY_RESULT,
  POSTS_QUERY_RESULT,
  PROJECT_QUERY_RESULT,
  PROJECTS_QUERY_RESULT,
  SanityImageCrop,
  SanityImageHotspot,
  SETTINGS_QUERY_RESULT,
} from './sanity.types';

// Convenience aliases over the types generated by `npm run typegen`.

export type SiteSettings = NonNullable<SETTINGS_QUERY_RESULT>;
export type Page = NonNullable<PAGE_QUERY_RESULT>;
export type PageSection = NonNullable<Page['sections']>[number];
export type SectionOf<T extends PageSection['_type']> = Extract<PageSection, { _type: T }>;

export type Post = NonNullable<POST_QUERY_RESULT>;
export type PostCard = POSTS_QUERY_RESULT[number];
export type Project = NonNullable<PROJECT_QUERY_RESULT>;
export type ProjectCard = PROJECTS_QUERY_RESULT[number];

export type Seo = Page['seo'];

/** Structural type matching every image projection produced by `imageFields`. */
export interface SanityImage {
  asset: {
    _id: string;
    url: string | null;
    metadata: {
      lqip: string | null;
      dimensions: { width: number | null; height: number | null } | null;
    } | null;
  } | null;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
}

/** Structural type matching every link projection produced by `linkFields`. */
export interface SanityLink {
  label: string | null;
  kind: 'external' | 'internal' | null;
  path: string | null;
  url: string | null;
  style: 'primary' | 'secondary' | 'text' | null;
  internal: { _type: 'page' | 'post' | 'project'; slug: string | null } | null;
}
